services:
  redis:
    image: redis:${REDIS_VERSION:-7-alpine}
    ports:
      - "${REDIS_PORT:-6379}:6379"
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    env_file:
      - .env
    volumes:
      - redis_data:/data
    restart: ${RESTART_POLICY:-unless-stopped}
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "PING"]
      interval: 30s
      timeout: 10s
      retries: 3

  api:
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:${REDIS_PORT:-6379}/0

  redis-commander:
    environment:
      - REDIS_HOSTS=local:redis:${REDIS_PORT:-6379}:0:${REDIS_PASSWORD}

volumes:
  redis_data:
    name: ${COMPOSE_PROJECT_NAME}-redis-data
