services:
  mongodb:
    image: mongo:${MONGO_VERSION:-7.0}
    ports:
      - "${MONGO_PORT:-27017}:27017"
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${DB_NAME}
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: ${RESTART_POLICY:-unless-stopped}
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  api:
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      - MONGO_URI=mongodb://${APP_DB_USER}:${APP_DB_PASSWORD}@mongodb:${MONGO_PORT:-27017}/${DB_NAME}?authSource=${DB_NAME}

  mongo-express:
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb:${MONGO_PORT:-27017}/${DB_NAME}?authSource=admin
volumes:
  mongodb_data:
    name: ${COMPOSE_PROJECT_NAME}-mongodb-data
  mongodb_config:
    name: ${COMPOSE_PROJECT_NAME}-mongodb-config
