services:
  api:
    build:
      target: development
    ports:
      - "${WEB_HOST_PORT:-5173}:${WEB_CONTAINER_PORT:-5173}"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --no-verbose --tries=1 --spider http://localhost:${API_CONTAINER_PORT:-3000}/api/health && wget --no-verbose --tries=1 --spider http://localhost:${WEB_CONTAINER_PORT:-5173}/ || exit 1",
        ]
    volumes:
      - ./packages/collab/src:/app/packages/collab/src
      - ./packages/db/src:/app/packages/db/src
      - ./packages/seed/src:/app/packages/seed/src
      - ./packages/ui/src:/app/packages/ui/src
      - ./apps/api/src:/app/apps/api/src
      - ./apps/web/src:/app/apps/web/src
      - ./apps/web/public:/app/apps/web/public
      - ./apps/web/index.html:/app/apps/web/index.html
    stdin_open: true
    tty: true
